# Generated by Django 2.2.6 on 2023-03-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230209_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Напишите сюда свой текст', max_length=100, verbose_name='Текст'),
        ),
    ]
